### ISSUE TITLE
request

### ISSUE THREAD

**Issue by NLPerLee** [zhangjiancong/MarketSpider#10]
京东和淘宝可否加一个销量的统计数据

**Comment by zhangjiancong** [comment]
淘宝网页显示的是支付人数，不是具体数值都是"1万+","2000+"之类的。
京东网页显示的是评价数，也是一个近似值。

感觉都不太符合销量这个概念，所以就没有。

**Comment by NLPerLee** [comment]
十分感谢解答；另外我觉得是不是可以做一个评价数的统计，一般来说评价数越多卖的越好，可以做定性用。最近在做这方面统计，你的程序帮助很大，十分感谢。





发自我的iPhone


------------------ Original ------------------
From: 张健聪 ***@***.***&gt;
Date: Tue,Jul 18,2023 11:55 AM
To: zhangjiancong/MarketSpider ***@***.***&gt;
Cc: NLPerLee ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zhangjiancong/MarketSpider] request (Issue #10)





 
淘宝网页显示的是支付人数，不是具体数值都是"1万+","2000+"之类的。
 京东网页显示的是评价数，也是一个近似值。
 
感觉都不太符合销量这个概念，所以就没有。

**Comment by NLPerLee** [comment]
对，京东可以从文本提取出评价这个参数。
淘宝不知道可不可以提取“已售”这个关键词。

发自我的iPhone


------------------ Original ------------------
From: 张健聪 ***@***.***&gt;
Date: Tue,Jul 18,2023 10:18 PM
To: zhangjiancong/MarketSpider ***@***.***&gt;
Cc: NLPerLee ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zhangjiancong/MarketSpider] request (Issue #10)





 
京东没问题的可以加上，淘宝还真没有看到在什么地方会显示评价总数😭。

**Comment by zhangjiancong** [comment]
淘宝新版界面添加了XXX人已付款的显示，已经更改相关代码可以正常提取。
京东的付款提取也已经在路上了。
