### ISSUE TITLE
拼多多有什么快捷方式吗

### ISSUE THREAD

**Issue by omaiyiwa** [zhangjiancong/MarketSpider#4]
不能保存第一页是什么原因，可以获取某个店铺里各个商品的规格、图片、视频对应价格嘛

**Comment by zhangjiancong** [comment]
不能保存第一页是因为第一页信息在页面请求中，还没有清晰的分离出来（有点嫌麻烦后来也不想弄了）。
目前这个项目面向的是**一个关键词**下的各个商品的ID、名称、图片链接、价格、店铺ID。
总之，pdd没有正经电脑版，项目主要用的selenium技术栈有点不太合适，手动这个办法纯粹是有需求才想的折中的方案；如果真的是有需求还是建议看看别的项目哦。
