### ISSUE TITLE
拼多多 HAR文件

### ISSUE THREAD

**Issue by lzl2040** [zhangjiancong/MarketSpider#6]
拼多多没有网页版，它的HAR文件怎么获取呢

**Comment by zhangjiancong** [comment]
可访问未被证实的网页版：**https://mobile.yangkeduo.com/**
为什么认为它是拼多多网页版主要基于以下几个原因：

- yangkeduo.com经ICP备案查询是“上海寻梦信息技术有限公司”主办的，同时www.yangkeduo.com也是拼多多app的官网

- 打开mobile.yangkeduo.com界面和APP一模一样，甚至一度让我怀疑APP是个浏览器套壳😅

- 在这上面登录会踢掉APP上的登录状态

- 通过关键词搜索可以获得近似于APP的结果，重合度在小范围测试中在80%以上

- 商品链接可通过手机浏览器正常拉起APP，在微信中打开也可正确看到对应的商品
